apiVersion: v1
kind: Service
metadata:
  name: {{ include "node-red.name" . }}
  labels:
    {{- include "node-red.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: redport
  selector:
    app: node-red
  sessionAffinity: None
  type: {{ .Values.service.type }}
